
project_id = "toigsarjwwediuelpxvi"
runtime = "nodejs"
version = 1
max_execution_time = 120  # Increased to 120 seconds (2 minutes) to handle more complex generation

# Retry policy
[http]
max_retries = 8  # Increased to 8 retries
retry_backoff_exponent = 2
max_retry_delay = 20   # Increased to 20 seconds

# Cache settings for the function - disabled for unique question generation
[cache]
cache_control = "no-cache"
