import React, { useState } from "react";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import { subjects } from "@/utils/subjects";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { ArrowRight, Check, ClipboardList, Clock, BarChart, ChevronLeft, ChevronRight, Brain, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import ExamQuestion from "@/components/Exam/ExamQuestion";
import AIAssistantButton from "@/components/AIAssistant/AIAssistantButton";
import AIAssistantDialog from "@/components/AIAssistant/AIAssistantDialog";
import { 
  Select, 
  SelectContent, 
  SelectItem, 
  SelectTrigger, 
  SelectValue 
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";

const EXAM_DURATION = 60; // minutes

const Exam = () => {
  const { toast } = useToast();
  const [selectedSubject, setSelectedSubject] = useState("");
  const [examType, setExamType] = useState("practice");
  const [questionCount, setQuestionCount] = useState(10);
  const [loading, setLoading] = useState(false);
  const [unitObjective, setUnitObjective] = useState("");
  
  // Exam state
  const [examStarted, setExamStarted] = useState(false);
  const [examQuestions, setExamQuestions] = useState<any[]>([]);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [examCompleted, setExamCompleted] = useState(false);
  
  // AI Assistant
  const [aiDialogOpen, setAiDialogOpen] = useState(false);

  // Get the selected subject object
  const selectedSubjectObj = subjects.find(s => s.id === selectedSubject);
  
  const handleGenerateExam = async () => {
    if (!selectedSubject) {
      toast({
        title: "Subject Required",
        description: "Please select a subject to continue",
        variant: "destructive",
      });
      return;
    }
    
    setLoading(true);
    
    try {
      // Generate challenging questions (always hard difficulty)
      const result = await supabase.functions.invoke("ai-generate-questions", {
        body: {
          subject: selectedSubjectObj?.name || "",
          count: questionCount,
          unitObjective: unitObjective.trim() || undefined,
          challengeLevel: "advanced",
          instructionType: "challenging"
        }
      });
      
      const data = result.data;
      const error = result.error;
      
      if (error) {
        throw error;
      }
      
      if (!data?.questions || data.questions.length === 0) {
        throw new Error("No questions were generated. The AI might need a moment to warm up, or there might not be enough context for the selected subject and learning objective.");
      }
      
      // Start the exam with the generated questions
      setExamQuestions(data.questions);
      setExamStarted(true);
      setCurrentQuestionIndex(0);
      setAnswers({});
      setExamCompleted(false);
      
      // Check if we have the requested number of questions
      if (data.questions.length < questionCount) {
        toast({
          title: "Limited Questions Available",
          description: `Only ${data.questions.length} questions could be generated by the AI for ${selectedSubjectObj?.name}. This might be due to the specificity of the learning objective.`,
          variant: "default",
        });
      } else {
        toast({
          title: "Exam Ready - Advanced Questions Generated",
          description: `${data.questions.length} challenging questions have been freshly created by AI based on your requirements. Good luck!`
        });
      }
      
    } catch (error) {
      console.error("Error generating questions:", error);
      toast({
        title: "Generation Failed",
        description: "Failed to generate questions. The AI service might be temporarily unavailable or need more specific inputs.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };
  
  const handleSelectAnswer = (questionId: string, answer: string) => {
    setAnswers(prev => ({
      ...prev,
      [questionId]: answer
    }));
  };
  
  const handleNextQuestion = () => {
    if (currentQuestionIndex < examQuestions.length - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    } else {
      handleFinishExam();
    }
  };
  
  const handlePrevQuestion = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(prev => prev - 1);
    }
  };
  
  const handleFinishExam = () => {
    let correctCount = 0;
    examQuestions.forEach(question => {
      if (answers[question.id] === question.correct_answer) {
        correctCount++;
      }
    });
    
    const score = Math.round((correctCount / examQuestions.length) * 100);
    
    toast({
      title: "Exam Completed",
      description: `Your score: ${score}% (${correctCount}/${examQuestions.length})`,
    });
    
    setExamCompleted(true);
  };
  
  const currentQuestion = examQuestions[currentQuestionIndex];
  
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      
      <main className="flex-grow pt-20">
        {!examStarted ? (
          <section className="py-10 md:py-16 bg-secondary/30">
            <div className="container px-4 md:px-6">
              <div className="flex flex-col items-center text-center mb-8">
                <div className="inline-flex items-center rounded-full bg-primary/10 px-3 py-1 text-sm font-medium text-primary mb-4">
                  <ClipboardList className="mr-1 size-3.5" />
                  <span>Test Your Knowledge</span>
                </div>
                
                <h1 className="text-3xl font-bold tracking-tight md:text-4xl mb-4">
                  AI-Generated Advanced Exams
                </h1>
                
                <p className="max-w-[700px] text-muted-foreground md:text-lg">
                  Practice with dynamically generated challenging questions created by our AI system.
                  Each question is crafted specifically for your selected subject and learning objectives
                  to test deep understanding and application.
                </p>
              </div>
              
              <div className="mx-auto max-w-3xl">
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center">
                      Generate Your Advanced Exam <Sparkles className="ml-2 size-4 text-yellow-500" />
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-6">
                      <div>
                        <Label className="block text-sm font-medium mb-2">
                          Exam Type
                        </Label>
                        <div className="flex space-x-4">
                          <div 
                            className={`flex items-center justify-center px-4 py-2 rounded-md cursor-pointer border transition-colors ${examType === "practice" ? "bg-primary text-primary-foreground border-primary" : "bg-background border-input hover:bg-accent hover:text-accent-foreground"}`}
                            onClick={() => setExamType("practice")}
                          >
                            <Check className="mr-2 size-4" />
                            <span>Practice Mode</span>
                          </div>
                          <div 
                            className={`flex items-center justify-center px-4 py-2 rounded-md cursor-pointer border transition-colors ${examType === "timed" ? "bg-primary text-primary-foreground border-primary" : "bg-background border-input hover:bg-accent hover:text-accent-foreground"}`}
                            onClick={() => setExamType("timed")}
                          >
                            <Clock className="mr-2 size-4" />
                            <span>Timed Exam</span>
                          </div>
                        </div>
                        <p className="text-sm text-muted-foreground mt-2">
                          {examType === "practice" 
                            ? "Take your time to answer challenging questions and see explanations for each answer."
                            : `Simulate the real exam experience with timed conditions (${EXAM_DURATION} minutes).`
                          }
                        </p>
                      </div>
                      
                      <div>
                        <Label htmlFor="subject" className="block text-sm font-medium mb-2">
                          Subject
                        </Label>
                        <Select
                          value={selectedSubject}
                          onValueChange={setSelectedSubject}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select a subject" />
                          </SelectTrigger>
                          <SelectContent>
                            {subjects.map((subject) => (
                              <SelectItem key={subject.id} value={subject.id}>
                                {subject.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <div>
                        <Label htmlFor="unitObjective" className="block text-sm font-medium mb-2">
                          Learning Objective (Optional)
                        </Label>
                        <Input
                          id="unitObjective"
                          placeholder="E.g., Understand photosynthesis process in plants"
                          value={unitObjective}
                          onChange={(e) => setUnitObjective(e.target.value)}
                          className="w-full"
                        />
                        <p className="text-sm text-muted-foreground mt-2">
                          Specify what you want to learn to get more targeted challenging questions
                        </p>
                      </div>
                      
                      <div>
                        <Label htmlFor="questionCount" className="block text-sm font-medium mb-2">
                          Number of Questions
                        </Label>
                        <Select
                          value={questionCount.toString()}
                          onValueChange={(value) => setQuestionCount(Number(value))}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select question count" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="5">5 questions</SelectItem>
                            <SelectItem value="10">10 questions</SelectItem>
                            <SelectItem value="15">15 questions</SelectItem>
                            <SelectItem value="20">20 questions</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      
                      <Button 
                        onClick={handleGenerateExam} 
                        className="mt-2 w-full"
                        disabled={loading}
                      >
                        {loading ? (
                          "AI Generating Advanced Questions..."
                        ) : (
                          <>Start Advanced Exam <Sparkles className="ml-2 size-4 text-yellow-500" /><ArrowRight className="ml-2 size-4" /></>
                        )}
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </section>
        ) : (
          <section className="py-10">
            <div className="container px-4 md:px-6">
              <div className="mx-auto max-w-3xl">
                <div className="mb-8">
                  <Button variant="outline" onClick={() => setExamStarted(false)} className="mb-4">
                    <ChevronLeft className="mr-2 size-4" /> Back to Setup
                  </Button>
                  
                  <div className="flex justify-between items-center mb-4">
                    <h2 className="text-2xl font-bold">
                      {examType === "practice" ? "Practice Exam" : "Timed Exam"}
                    </h2>
                    <div className="text-sm text-muted-foreground">
                      Question {currentQuestionIndex + 1} of {examQuestions.length}
                    </div>
                  </div>
                  
                  <div className="h-2 w-full bg-secondary rounded-full overflow-hidden mb-6">
                    <div 
                      className="h-full bg-primary"
                      style={{ width: `${((currentQuestionIndex + 1) / examQuestions.length) * 100}%` }}
                    />
                  </div>
                </div>
                
                {currentQuestion && (
                  <ExamQuestion
                    question={currentQuestion}
                    selectedAnswer={answers[currentQuestion.id] || null}
                    onSelectAnswer={(answer) => handleSelectAnswer(currentQuestion.id, answer)}
                    showCorrectAnswer={examCompleted}
                    questionNumber={currentQuestionIndex + 1}
                  />
                )}
                
                <div className="flex justify-between">
                  <Button 
                    variant="outline" 
                    onClick={handlePrevQuestion}
                    disabled={currentQuestionIndex === 0}
                  >
                    <ChevronLeft className="mr-2 size-4" /> Previous
                  </Button>
                  
                  {!examCompleted ? (
                    <Button 
                      onClick={handleNextQuestion}
                      disabled={!answers[currentQuestion?.id]}
                    >
                      {currentQuestionIndex < examQuestions.length - 1 ? (
                        <>Next <ChevronRight className="ml-2 size-4" /></>
                      ) : (
                        <>Finish Exam <Check className="ml-2 size-4" /></>
                      )}
                    </Button>
                  ) : (
                    <Button 
                      onClick={() => setExamStarted(false)}
                      variant="default"
                    >
                      Back to Exams
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </section>
        )}
        
        {!examStarted && (
          <section className="py-12">
            <div className="container px-4 md:px-6">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold">Recent Exams</h2>
                <Button variant="outline" size="sm">
                  View All
                </Button>
              </div>
              
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <div className="rounded-lg border bg-card p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700">
                      Mathematics
                    </span>
                    <span className="text-sm text-muted-foreground">2 days ago</span>
                  </div>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-medium">Practice Exam</h3>
                    <div className="flex items-center">
                      <BarChart className="mr-1 size-3.5 text-primary" />
                      <span className="font-medium">70%</span>
                    </div>
                  </div>
                  <Button variant="outline" size="sm" className="w-full">
                    Review Answers
                  </Button>
                </div>
                
                <div className="rounded-lg border bg-card p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-700">
                      Biology
                    </span>
                    <span className="text-sm text-muted-foreground">1 week ago</span>
                  </div>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-medium">Timed Exam</h3>
                    <div className="flex items-center">
                      <BarChart className="mr-1 size-3.5 text-primary" />
                      <span className="font-medium">85%</span>
                    </div>
                  </div>
                  <Button variant="outline" size="sm" className="w-full">
                    Review Answers
                  </Button>
                </div>
                
                <div className="rounded-lg border bg-card p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="rounded-full bg-purple-50 px-2 py-1 text-xs font-medium text-purple-700">
                      Chemistry
                    </span>
                    <span className="text-sm text-muted-foreground">2 weeks ago</span>
                  </div>
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="font-medium">Past Paper (2022)</h3>
                    <div className="flex items-center">
                      <BarChart className="mr-1 size-3.5 text-primary" />
                      <span className="font-medium">65%</span>
                    </div>
                  </div>
                  <Button variant="outline" size="sm" className="w-full">
                    Review Answers
                  </Button>
                </div>
              </div>
            </div>
          </section>
        )}
      </main>
      
      <AIAssistantButton onClick={() => setAiDialogOpen(true)} />
      <AIAssistantDialog open={aiDialogOpen} onOpenChange={setAiDialogOpen} />
      
      <Footer />
    </div>
  );
};

export default Exam;
